version: '3'

services:
  db:
    image: mysql:5.7.29
    volumes:
      - ./db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: order_tool
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  web:
    build:
       context: ./django-backend/
       dockerfile: dockerfile
       args:
         USER: ${USER}
         UID: ${UID}
         GID: ${UID}
    command: ['bash', './main.sh']
    restart: always
    volumes:
      - ./django-backend/:/home/${USER}
    ports:
      - "8000:8000"
    depends_on:
      - db
