version: '3'

services: 
  db:
    image: mysql:5.7.29
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: order_tool
    ports:
      - "9530:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  web:
    build:
       context: ./django-backend/
       dockerfile: dockerfile
    command: ['bash', './main.sh']
    restart: always
    volumes:
      - ./django-backend/:/code
    ports:
      - "8088:8000"
    depends_on:
      - db
  client:
    build:
      context: ./client
    volumes:
      - node_modules:/app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    ports:
      - "3000:3000"
volumes:
  mysql:
  node_modules:
