version: '3'

services:
  db:
    image: mysql:5.7.29
    volumes:
      - /home/jimmyliao/Desktop/db/order-tool:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3306:3306"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/demo
    ports:
      - "8000:8000"
    depends_on:
      - db
